# Generated by Django 4.1.3 on 2023-01-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
