# Generated by Django 4.1.3 on 2023-01-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_post_email_alter_post_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
